// GLOSARIO DE LA APP (versión corta de docs/glosario.md): término, definición de 1-2 frases, ejemplo opcional
// y cómo lo llaman Business Central (bc) y SAP (sap). Lo usan <Term id="…"> (el ⓘ con globo) y la página Glosario.
export const GLOSSARY = {
  // Partida doble y asientos
  debit: { bc: 'Debit Amount', sap: 'Debit (S)',
    es: { term: 'Debe', def: 'Lado izquierdo de una cuenta. Aumentan por el Debe lo que tienes (caja, bancos, clientes) y los gastos.', ex: 'Cobras 100 € en el banco: 572 al Debe.' },
    en: { term: 'Debit', def: 'Left side of an account. Assets (cash, bank, customers) and expenses increase on the debit side.', ex: 'You collect €100 in the bank: 572 debit.' } },
  credit: { bc: 'Credit Amount', sap: 'Credit (H)',
    es: { term: 'Haber', def: 'Lado derecho de una cuenta. Aumentan por el Haber lo que debes (proveedores, préstamos), el capital y los ingresos.', ex: 'Vendes por 100 €: 700 al Haber.' },
    en: { term: 'Credit', def: 'Right side of an account. Liabilities (suppliers, loans), equity and income increase on the credit side.', ex: 'You sell for €100: 700 credit.' } },
  doubleEntry: { bc: 'Double-entry', sap: 'Double-entry',
    es: { term: 'Partida doble', def: 'Todo hecho económico mueve al menos dos cuentas, y la suma del Debe es siempre igual a la del Haber.' },
    en: { term: 'Double entry', def: 'Every transaction moves at least two accounts, and total debits always equal total credits.' } },
  entry: { bc: 'G/L Entries (Document)', sap: 'Accounting document (BKPF)',
    es: { term: 'Asiento', def: 'Anotación de un hecho económico en la contabilidad: una fecha, un concepto y varias líneas (apuntes) que cuadran.' },
    en: { term: 'Journal entry', def: 'Record of a transaction in the books: a date, a description and several lines that balance.' } },
  draft: { bc: 'General Journal line', sap: 'Parked document',
    es: { term: 'Borrador', def: 'Asiento guardado pero no contabilizado: se puede cambiar o borrar y no cuenta en los informes.' },
    en: { term: 'Draft', def: 'An entry saved but not posted: it can be changed or deleted and does not count in the reports.' } },
  posting: { bc: 'Post', sap: 'Post',
    es: { term: 'Contabilizar', def: 'Dar por definitivo un asiento: recibe su número correlativo, entra en los libros y ya no se puede cambiar.' },
    en: { term: 'Post', def: 'Make an entry final: it gets its sequential number, goes into the books and can no longer be changed.' } },
  reversal: { bc: 'Reverse Transaction', sap: 'Reverse document (FB08)',
    es: { term: 'Contraasiento', def: 'Asiento igual que otro pero con el Debe y el Haber cambiados: lo anula sin borrarlo, dejando rastro.' },
    en: { term: 'Reversal entry', def: 'An entry identical to another with debit and credit swapped: it cancels it without deleting it, leaving a trail.' } },
  subaccount: { bc: 'G/L Account (Posting)', sap: 'G/L account (SKB1)',
    es: { term: 'Subcuenta', def: 'Cuenta de último nivel donde se apunta, con todos sus dígitos. Cuelga de una cuenta del PGC.', ex: '57200001 (un banco) cuelga de la 572 (Bancos).' },
    en: { term: 'Posting account', def: 'Last-level account where amounts are posted, with all its digits. It belongs to a chart-of-accounts account.', ex: '57200001 (a bank) belongs to 572 (Banks).' } },
  chart: { bc: 'Chart of Accounts', sap: 'Chart of accounts (SKA1)',
    es: { term: 'Plan General Contable (PGC)', def: 'Norma española (RD 1514/2007) que fija las cuentas, su numeración y cómo se valoran las operaciones.' },
    en: { term: 'Spanish GAAP (PGC)', def: 'Spanish standard (RD 1514/2007) that sets the accounts, their numbering and how transactions are measured.' } },
  partner: { bc: 'Customer / Vendor', sap: 'Business Partner',
    es: { term: 'Tercero', def: 'Cliente, proveedor, acreedor o deudor. Cada uno tiene su subcuenta (430, 400, 410, 440) y su NIF.' },
    en: { term: 'Business partner', def: 'Customer, supplier, creditor or debtor. Each has its own account (430, 400, 410, 440) and tax ID.' } },
  fiscalYear: { bc: 'Accounting Period (year)', sap: 'Fiscal year',
    es: { term: 'Ejercicio', def: 'Periodo de 12 meses al que se refieren las cuentas anuales. Se abre, se lleva y se cierra.' },
    en: { term: 'Fiscal year', def: 'The 12-month period the annual accounts refer to. It is opened, kept and closed.' } },
  closing: { bc: 'Close Income Statement', sap: 'Balance carryforward (FAGLGVTR)',
    es: { term: 'Cierre del ejercicio', def: 'Regularización (gastos e ingresos a la 129), asiento de cierre (todo a cero) y apertura del ejercicio siguiente.' },
    en: { term: 'Year-end closing', def: 'Closing the P&L into account 129, the closing entry (all to zero) and the opening entry of the next year.' } },

  // Libros e informes
  journal: { bc: 'G/L Register', sap: 'Journal',
    es: { term: 'Libro diario', def: 'Todos los asientos por orden de fecha y número. Es obligatorio (Código de Comercio, art. 28).' },
    en: { term: 'General journal', def: 'All entries in date and number order. It is a legal book in Spain.' } },
  ledger: { bc: 'G/L Account Statement', sap: 'Line items (FBL3N)',
    es: { term: 'Libro mayor', def: 'Los movimientos de una sola cuenta con su saldo acumulado.' },
    en: { term: 'General ledger', def: 'The movements of a single account with its running balance.' } },
  trialBalance: { bc: 'Trial Balance', sap: 'Balance list (S_ALR_87012277)',
    es: { term: 'Balance de sumas y saldos', def: 'Por cada cuenta, la suma del Debe, la del Haber y su saldo. Si la contabilidad cuadra, los totales coinciden.' },
    en: { term: 'Trial balance', def: 'For each account, total debits, total credits and the balance. If the books balance, the totals match.' } },
  inverseBalance: { bc: '—', sap: '—',
    es: { term: 'Saldo anómalo', def: 'Saldo contrario a la naturaleza de la cuenta: una caja acreedora o un cliente con saldo acreedor. Suele ser un error o una reclasificación pendiente.' },
    en: { term: 'Inverse balance', def: 'A balance against the nature of the account: cash in credit or a customer in credit. Usually an error or a pending reclassification.' } },
  balance: { bc: 'Balance Sheet', sap: 'Balance sheet',
    es: { term: 'Balance de situación', def: 'Foto del patrimonio en una fecha: lo que la empresa tiene (activo) y cómo se financia (patrimonio neto y pasivo).' },
    en: { term: 'Balance sheet', def: 'A snapshot at a date: what the company owns (assets) and how it is financed (equity and liabilities).' } },
  pyg: { bc: 'Income Statement', sap: 'P&L statement',
    es: { term: 'Cuenta de pérdidas y ganancias', def: 'Ingresos menos gastos de un periodo: el resultado (beneficio o pérdida).' },
    en: { term: 'Income statement', def: 'Income minus expenses for a period: the result (profit or loss).' } },
  equity: { bc: 'Equity', sap: 'Equity',
    es: { term: 'Patrimonio neto', def: 'Lo que es de los socios: capital, reservas y resultados. Activo menos pasivo.' },
    en: { term: 'Equity', def: 'What belongs to the owners: capital, reserves and results. Assets minus liabilities.' } },
  cashflow: { bc: 'Cash Flow Statement', sap: 'Cash flow statement',
    es: { term: 'Estado de flujos de efectivo (EFE)', def: 'De dónde viene y a dónde va la caja: actividades de explotación, inversión y financiación.', ex: 'Método directo (cobros y pagos) o indirecto (desde el resultado).' },
    en: { term: 'Cash flow statement', def: 'Where cash comes from and where it goes: operating, investing and financing activities.', ex: 'Direct method (receipts and payments) or indirect (from the result).' } },
  ratio: { bc: 'KPI / Analysis View', sap: 'KPI',
    es: { term: 'Ratio', def: 'Cociente entre dos partidas que resume la salud de la empresa: liquidez, endeudamiento, rentabilidad.', ex: 'Liquidez = activo corriente / pasivo corriente.' },
    en: { term: 'Ratio', def: 'A quotient of two items that summarises the company’s health: liquidity, leverage, profitability.', ex: 'Current ratio = current assets / current liabilities.' } },
  workingCapital: { bc: 'Working Capital', sap: 'Working capital',
    es: { term: 'Fondo de maniobra', def: 'Activo corriente menos pasivo corriente: el colchón para pagar las deudas a corto plazo.' },
    en: { term: 'Working capital', def: 'Current assets minus current liabilities: the cushion to pay short-term debts.' } },
  depreciation: { bc: 'Depreciation', sap: 'Depreciation (AFAB)',
    es: { term: 'Amortización', def: 'Reparto del coste de un inmovilizado a lo largo de su vida útil: gasto (68x) contra amortización acumulada (28x).' },
    en: { term: 'Depreciation', def: 'Spreading a fixed asset’s cost over its useful life: expense (68x) against accumulated depreciation (28x).' } },

  // Impuestos y facturas
  vat: { bc: 'VAT', sap: 'Tax code (MWSKZ)',
    es: { term: 'IVA', def: 'Impuesto sobre el Valor Añadido, en la Península y Baleares. La empresa lo cobra en sus ventas y lo paga en sus compras; ingresa la diferencia.', ex: 'Tipos: 21 %, 10 %, 4 %.' },
    en: { term: 'VAT (IVA)', def: 'Value Added Tax, in mainland Spain and the Balearics. The company charges it on sales and pays it on purchases, paying over the difference.', ex: 'Rates: 21%, 10%, 4%.' } },
  igic: { bc: 'VAT (local)', sap: 'Tax code',
    es: { term: 'IGIC', def: 'Impuesto General Indirecto Canario: el equivalente del IVA en Canarias, con tipos propios.', ex: 'Tipo general 7 %; se declara en el modelo 420.' },
    en: { term: 'IGIC', def: 'Canary Islands General Indirect Tax: the Canary Islands’ equivalent of VAT, with its own rates.', ex: 'Standard rate 7%; filed on form 420.' } },
  inputTax: { bc: 'Purchase VAT', sap: 'Input tax',
    es: { term: 'IVA / IGIC soportado (472)', def: 'El impuesto que te cobran tus proveedores. Es un derecho frente a Hacienda: se resta en la liquidación.' },
    en: { term: 'Input VAT / IGIC (472)', def: 'The tax your suppliers charge you. It is a claim on the tax office: it is deducted in the settlement.' } },
  outputTax: { bc: 'Sales VAT', sap: 'Output tax',
    es: { term: 'IVA / IGIC repercutido (477)', def: 'El impuesto que cobras a tus clientes. Es una deuda con Hacienda hasta que lo liquidas.' },
    en: { term: 'Output VAT / IGIC (477)', def: 'The tax you charge your customers. It is a debt to the tax office until you settle it.' } },
  taxBase: { bc: 'VAT Base', sap: 'Tax base',
    es: { term: 'Base imponible', def: 'Importe sobre el que se calcula el impuesto: el precio sin IVA ni IGIC.', ex: 'Base 1.000 € × 21 % = 210 € de IVA.' },
    en: { term: 'Tax base', def: 'The amount the tax is calculated on: the price before VAT or IGIC.', ex: 'Base €1,000 × 21% = €210 VAT.' } },
  invoice: { bc: 'Posted Purchase / Sales Invoice', sap: 'FB60 / FB70',
    es: { term: 'Factura', def: 'Documento de una compra o venta con sus bases, tipos y cuotas. Al registrarla, el ERP genera el asiento y el libro registro.' },
    en: { term: 'Invoice', def: 'Document of a purchase or sale with its bases, rates and taxes. When registered, the ERP creates the entry and the tax register line.' } },
  creditMemo: { bc: 'Credit Memo', sap: 'Credit memo',
    es: { term: 'Factura rectificativa', def: 'Factura que corrige otra (devolución, descuento, error). Nunca se modifica la original.' },
    en: { term: 'Credit memo', def: 'An invoice that corrects another (return, discount, error). The original is never changed.' } },
  settlement: { bc: 'Calc. and Post VAT Settlement', sap: 'RFUMSV00',
    es: { term: 'Liquidación de IVA / IGIC', def: 'Cada trimestre: repercutido menos soportado. Si sale positivo se paga; si es negativo, se compensa o se pide la devolución en el 4T.', ex: 'Modelos 303 (IVA) y 420 (IGIC).' },
    en: { term: 'VAT / IGIC settlement', def: 'Every quarter: output minus input tax. If positive it is paid; if negative it is carried forward or refunded in Q4.', ex: 'Forms 303 (VAT) and 420 (IGIC).' } },
  prorata: { bc: 'VAT % Non-deductible', sap: 'Non-deductible input tax',
    es: { term: 'Prorrata', def: 'Porcentaje del IVA soportado que se puede deducir cuando la empresa hace a la vez operaciones con y sin derecho a deducción.' },
    en: { term: 'Pro rata', def: 'The share of input VAT that can be deducted when the company has both taxable and exempt sales.' } },
  reverseCharge: { bc: 'Reverse Charge VAT', sap: 'Reverse charge',
    es: { term: 'Inversión del sujeto pasivo (ISP)', def: 'El comprador, no el vendedor, se repercute y se soporta el impuesto a la vez (autorrepercusión).', ex: 'Compras intracomunitarias, obras con subcontratas.' },
    en: { term: 'Reverse charge', def: 'The buyer, not the seller, accounts for the tax, charging and deducting it at the same time.', ex: 'Intra-EU purchases, subcontracted construction.' } },
  surcharge: { bc: 'Equivalence surcharge', sap: '—',
    es: { term: 'Recargo de equivalencia', def: 'Régimen de los minoristas personas físicas: su proveedor les cobra un recargo extra y ellos no presentan liquidación de IVA.' },
    en: { term: 'Equivalence surcharge', def: 'Regime for sole-trader retailers: their supplier charges an extra surcharge and they do not file VAT returns.' } },
  withholding: { bc: 'IRPF withholding', sap: 'Withholding tax',
    es: { term: 'Retención de IRPF', def: 'Parte de la factura de un profesional o de un alquiler que el pagador ingresa en Hacienda por cuenta del perceptor (4751).', ex: 'Modelos 111 (profesionales) y 115 (alquileres).' },
    en: { term: 'Income tax withholding', def: 'Part of a professional’s or landlord’s invoice that the payer pays to the tax office on their behalf (4751).', ex: 'Forms 111 (professionals) and 115 (rents).' } },
  accrual: { bc: 'Accrual', sap: 'Accrual',
    es: { term: 'Devengo', def: 'Los ingresos y gastos se anotan cuando ocurren, no cuando se cobran o se pagan.' },
    en: { term: 'Accrual', def: 'Income and expenses are recorded when they occur, not when they are collected or paid.' } },
}

// Pantalla de la empresa → término que la explica (el ⓘ junto a la ruta "Informes › Balance")
export const SECTION_TERM = {
  entry: 'entry', journal: 'journal', closing: 'closing', invoices: 'invoice', settlement: 'settlement',
  withholdings: 'withholding', prorata: 'prorata', taxes: 'vat', balance: 'balance', pyg: 'pyg',
  cashflow: 'cashflow', ratios: 'ratio', reports: 'trialBalance', accounts: 'subaccount', partners: 'partner',
}
